#### 2023-04-03

##### 1교시

In [5]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv' ) 

In [6]:
df.columns = df.columns.str.capitalize() 

In [7]:
df.columns = sorted(df.columns)

In [9]:
# 알파벳 순서대로 칼럼을 나열하시오.
sorted(df.columns)

['Acceleration',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Model-year',
 'Mpg',
 'Weight']

In [10]:
#  loc, iloc, NaN 은 어떤 단어의 줄임말일까?
# loc = location
# iloc = integer location
# nan = not a number 

In [12]:
employ = pd.read_csv('https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv ')

In [13]:
employ[:3]

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald  OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas     Grant    DGRANT  650.507.9844  13-JAN-08   
2          200   Jennifer    Whalen   JWHALEN  515.123.4444  17-SEP-03   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50  
2   AD_ASST    4400             -         101             10

In [14]:
# employ id 가 200이상이고 salary가 5000넘는 사람 수는 몇 명인가?

In [15]:
employ[(employ['EMPLOYEE_ID']>=200)&(employ['SALARY']>5000)].__len__() 

6

In [24]:
# np로 1부터 20까지 배열을 구하는 코드는?
import numpy as np
arr = np.arange(1,21)

In [25]:
# arr의 누적합을 구하면?
arr.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210])

In [85]:
# 1부터 100까지의 수 중 랜덤으로 10개를 뽑은 후 배열을 비교하여 큰수를 구하시오.
a = np.random.randint(1,101,10)
b = np.random.randint(1,101,10)
np.maximum(a,b)

array([ 55,  57,  91,  95,  50, 100,  70,  68,  12,  86])

In [91]:
# titanic 칼럼에서 k로 시작하는 행만 추출하시오.
titanic=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
titanic['Ticket'].str.contains('^p.+').sum()

0

In [93]:
titanic["Name"].str.contains(".+Mrs.+").sum()

129

In [94]:
# 칼럼 Survived 에서 생존으로 이름바꾸기
titanic.rename(columns={'Survived':'생존'},inplace=True)

In [104]:
# 25명의 수학점수, 평균:70 , 표준 편차: 8
math = np.random.randn(25)*8 + 70
# np.random.normal(70,8,25)

In [105]:
# 55점 미만인 학생들은 방과후 수업을 들어야한다. 이 학생수를 구하시오.
(math < 55).sum()

1

In [106]:
# math 소수점 이하 두자리만 표현
math.round(2)

array([68.31, 77.7 , 52.67, 71.29, 68.84, 59.49, 64.57, 67.98, 75.  ,
       74.52, 70.52, 72.93, 76.45, 66.98, 66.7 , 70.38, 72.62, 71.89,
       69.88, 65.63, 66.88, 67.25, 61.5 , 83.6 , 85.48])

In [119]:
np.random.RandomState(1234)
scores = np.random.randint(8,11,(2,10))
scores

array([[ 8,  8, 10, 10, 10,  8,  9, 10,  9,  9],
       [10,  8, 10,  9, 10, 10,  8,  8,  9,  9]])

In [120]:
a = scores[0]
b = scores[1]
a+b

array([18, 16, 20, 19, 20, 18, 17, 18, 18, 18])

##### 2교시

In [122]:
df = pd.DataFrame(scores, index = ['A',"B"], columns = range(1,11))
df['총점']=df.sum(axis = 1)
df 

1  2   3   4   5   6  7   8  9  10  총점
A   8  8  10  10  10   8  9  10  9   9  91
B  10  8  10   9  10  10  8   8  9   9  91

In [123]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [124]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

##### 3교시

In [125]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000} 
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [128]:
pd.Series(sdata)
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [129]:
'Ohio' in sdata

True

In [130]:
s = pd.Series(sdata)
s

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [131]:
pd.isnull(s)

Ohio      False
Texas     False
Oregon    False
Utah      False
dtype: bool

In [133]:
pd.notnull(s)

Ohio      True
Texas     True
Oregon    True
Utah      True
dtype: bool

In [135]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)

In [136]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata, index=states)

In [137]:
obj4.name

In [139]:
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [145]:
# series 만들어 보기.
s = pd.Series([2,4,6,8])
s

0    2
1    4
2    6
3    8
dtype: int64

In [146]:
# index 를 추가해봅시다.
s.index = ['a','b','c','d']
s

a    2
b    4
c    6
d    8
dtype: int64

In [148]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 

In [150]:
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

##### 5교시

In [152]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 

In [153]:
s = pd.Series([2,4,6,8])
s 

0    2
1    4
2    6
3    8
dtype: int64

In [156]:
s.value_counts()

2    1
4    1
6    1
8    1
dtype: int64

In [157]:
s.index = ['a', 'b', 'c', 'd']
s 

a    2
b    4
c    6
d    8
dtype: int64

In [158]:
s['e']=2

In [160]:
s.values

array([2, 4, 6, 8, 2], dtype=int64)

In [161]:
s.astype('str') # 문자열로 바꾸기

a    2
b    4
c    6
d    8
e    2
dtype: object

In [162]:
map(str,s)

In [165]:
list(map(lambda x: x*10, s))

[20, 40, 60, 80, 20]

In [167]:
s[s.isin([2,4])]

a    2
b    4
e    2
dtype: int64

In [171]:
# 오하이오 만 추출하시오
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [169]:
frame[frame['state']=='Ohio']

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [173]:
frame[frame['state'].isin(['Ohio'])]

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

value_counts()
astype()
isin()

In [174]:
frame['dept']=range(6)
frame

state  year  pop  dept
0    Ohio  2000  1.5     0
1    Ohio  2001  1.7     1
2    Ohio  2002  3.6     2
3  Nevada  2001  2.4     3
4  Nevada  2002  2.9     4
5  Nevada  2003  3.2     5

In [175]:
# dept 칼럼 삭제하기
del frame['dept']
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [182]:
frame['eastern'] = frame['state'] == 'Ohio'
frame['state'].where

<bound method Series.where of 0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object>

In [183]:
# Ohio 는 Yes, 아니면 No
frame['estern'] = np.where(frame['state'] == 'Ohio','yes','no')
frame

state  year  pop  eastern estern
0    Ohio  2000  1.5     True    yes
1    Ohio  2001  1.7     True    yes
2    Ohio  2002  3.6     True    yes
3  Nevada  2001  2.4    False     no
4  Nevada  2002  2.9    False     no
5  Nevada  2003  3.2    False     no

In [184]:
frame3.index.name = '인덱스이름'
frame3.columns.name = '칼럼이름'
frame3

NameError: name 'frame3' is not defined

##### 6교시

In [185]:
obj = pd.Series(range(3),index = ['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [186]:
obj.index
obj.index[1]
obj.index[:2]

Index(['a', 'b'], dtype='object')

In [189]:
obj['d']=10
obj

a     0
b     1
c     2
d    10
dtype: int64

In [208]:
obj.index = ['a','b','c','a']
obj

a     0
b     1
c     2
a    10
dtype: int64

In [200]:
obj['a']

a     0
a    10
dtype: int64

In [211]:
obj=pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj 

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [212]:
obj = obj.reindex(['a', 'b', 'c', 'd'])
obj 

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [214]:
obj['c':'d']

c    3.6
d    4.5
dtype: float64

In [216]:
obj['a':'c']=3.0
obj

a    3.0
b    3.0
c    3.0
d    4.5
dtype: float64

In [217]:
df = pd.DataFrame(np.arange(1,17).reshape(4,4))
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [223]:
# 6 이하는 '0'으로 만들어라
np.where(df<=6,0,df)

array([[ 0,  0,  0,  0],
       [ 0,  0,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])