#### 2023-03-29

##### 1교시

In [5]:
import numpy as np
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
# 위 행렬의 대각 행렬을 구하시오.

In [6]:
np.diag(a)

array([ 1,  7, 13, 19, 25])

In [7]:
np.array([10,12,15,25,28,30,35,42,50]) 

array([10, 12, 15, 25, 28, 30, 35, 42, 50])

In [17]:
a = np.array([0,1,2,3,4])
b = np.array([[0],[4],[10],[20],[30]])
a+b
c = a+b

In [13]:
c[1::2,:3:2] 

array([[ 4,  6],
       [20, 22]])

In [21]:
np.tile(a,(2,3))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

In [24]:
a = np.array([[2,5,4], [3,1,9], [6,8,7]]) 

In [30]:
np.sort(a.T,axis=0)

array([[2, 1, 6],
       [4, 3, 7],
       [5, 9, 8]])

In [34]:
a = np.arange(1,5)
b = np.array([[0],[7], [14], [21]])
c = a+b 
c

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [22, 23, 24, 25]])

In [35]:
a = np.arange(1,29).reshape(4,-1)[:4,:4]
a

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [22, 23, 24, 25]])

In [37]:
a[1::2,1::2]

array([[ 9, 11],
       [23, 25]])

In [38]:
a=np.arange(1,7).reshape(2,3)
a
# 대각행렬을 구하는 3가지 방법

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.T
a.transpose()
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
# 다음 배열을 완성하세요.

In [61]:
a=np.ones((5,5))
a[:1]=2
a[2,2]=3
print(a)

[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 3. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### 2교시

In [65]:
a=np.arange(25).reshape(5,5)
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [66]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a[np.where(a%3==0)]

array([ 3,  6,  9, 12])

In [70]:
a = np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [71]:
np.max(a,axis=1)

array([225,  81,   9,  64, 196])

In [75]:
np.mean(a,axis=0)

array([81., 76., 73., 72., 73., 76.])

In [ ]:
# 랜덤으로 입력받은 수만큼 사람을 중복되지 않게 뽑아서, 
# "1번 문제는 000입니다."
# "2번 문제는 000입니다."
# "3번 문제는 000입니다."
# 로 출력해 주세요.

In [82]:
li = ( "강한샘", '곽유석', '현재은', '김경민', '권상지', '김기범', '김연준', '김인섭', '나윤찬', '남기훈', '도영현','장기영', '류소현', '문범식', '손수한', '옥윤호', '위지원', '윤민영', '장휘재', '조은정', '주기재', '황수림', 'miji')

In [83]:
def choice_person(num):
    person = random.sample(li, k=num)
    for i in range(num):
        print(f"{i+1}번 문제는 {person[i]}입니다.") 

##### 3교시

##### 시리즈

In [86]:
import pandas as pd

In [87]:
animals = ['Tiger','Bear','Cat']
animals

['Tiger', 'Bear', 'Cat']

In [88]:
s = pd.Series(animals)
s
# object = string = character

0    Tiger
1     Bear
2      Cat
dtype: object

In [89]:
type(s)

pandas.core.series.Series

##### 5교시

In [97]:
d={'a':1,'b':2,'c':3}
s=pd.Series(d)
s

a    1
b    2
c    3
dtype: int64

In [98]:
s['a']

1

##### 데이터 프레임

In [103]:
df=pd.DataFrame(np.arange(6).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [104]:
type(df)

pandas.core.frame.DataFrame

In [106]:
pd.DataFrame({'a':[1,2],'b':2,'c':3})

a  b  c
0  1  2  3
1  2  2  3

In [108]:
pd.DataFrame([4,5,6,7], index=['a','b','c','d'],columns=['A'])

A
a  4
b  5
c  6
d  7

In [111]:
pd.DataFrame(np.arange(16).reshape(4,4), index=['a','b','c','d'])

0   1   2   3
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [126]:
df = pd.DataFrame([[15,'남','남중'],[17,'여','여중']],
                    index=['철수','영희'],
                    columns=['나이','성별','학교'])
print(df)

    나이 성별  학교
철수  15  남  남중
영희  17  여  여중


In [114]:
df.index

Index(['철수', '영희'], dtype='object')

In [115]:
df.columns

Index(['나이', '성별', '학교'], dtype='object')

##### 행과 열 다루기

In [116]:
# 삭제하기
df.drop('철수')

나이 성별  학교
영희  17  여  여중

In [127]:
df.drop('철수', inplace=True)
df

나이 성별  학교
영희  17  여  여중

In [120]:
df.loc['영희',:]

나이    17
성별     여
학교    여중
Name: 영희, dtype: object

In [152]:
df = pd.DataFrame([[90,98,85,100],[80,89,95,90],[70,95,100,90]],
                    index=['서준','우현','인아'],
                    columns=['수학','영어','음악','체육'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [131]:
df = pd.DataFrame({'수학': [90, 80, 70], '영어' : [98,89, 95], 
                  '음악':[85, 95, 100], '체육' : [100, 90, 90]}) 
df

수학  영어   음악   체육
0  90  98   85  100
1  80  89   95   90
2  70  95  100   90

In [133]:
a=df.values
a

array([[ 90,  98,  85, 100],
       [ 80,  89,  95,  90],
       [ 70,  95, 100,  90]], dtype=int64)

In [134]:
a[0,0]

90

In [136]:
a[1,:]

array([80, 89, 95, 90], dtype=int64)

In [137]:
a[:,1]

array([98, 89, 95], dtype=int64)

In [138]:
df.iloc[0,0]

90

In [139]:
# df 는 array 가 아니다.

##### 6교시

In [141]:
df

수학  영어   음악   체육
0  90  98   85  100
1  80  89   95   90
2  70  95  100   90

In [142]:
df.iloc[0,:]

수학     90
영어     98
음악     85
체육    100
Name: 0, dtype: int64

In [157]:
df = pd.DataFrame([[90,98,85,100],[80,89,95,90],[70,95,100,90]],
                    index=['서준','우현','인아'],
                    columns=['수학','영어','음악','체육'])
df.loc[['서준'],:]

수학  영어  음악   체육
서준  90  98  85  100

In [158]:
# 수학,영어 칼럼만 뽑아내시오.
# 수학칼럼만 뽑아내시오.

In [164]:
df.iloc[:,[0,1]]

수학  영어
서준  90  98
우현  80  89
인아  70  95

In [162]:
df.iloc[:,[0]]

수학
서준  90
우현  80
인아  70

In [166]:
# df.loc[] = 행추출
# df[] = 열추출

##### 행과 열 이름 바꾸기

In [167]:
df.index

Index(['서준', '우현', '인아'], dtype='object')

In [168]:
df.index =[['준','현','아']]
df

수학  영어   음악   체육
준  90  98   85  100
현  80  89   95   90
아  70  95  100   90

In [169]:
df.index = ['서준','우현','인아']
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [171]:
df.rename(columns={"체육":"체"})

수학  영어   음악    체
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [172]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [185]:
import plotly.express as px
df = px.data.gapminder()
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [177]:
df.shape

(1704, 8)

In [178]:
df.head()

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4

In [186]:
# 행추출 하기
df=df.iloc[[100,200,300,400,500]]
df

country continent  year  lifeExp       pop     gdpPercap  \
100      Bangladesh      Asia  1972   45.252  70759295    630.233627   
200    Burkina Faso    Africa  1992   50.260   8878303    931.752773   
300        Colombia  Americas  1952   50.643  12350771   2144.115096   
400  Czech Republic    Europe  1972   70.290   9862158  13108.453600   
500         Eritrea    Africa  1992   49.991   3668440    582.858510   

    iso_alpha  iso_num  
100       BGD       50  
200       BFA      854  
300       COL      170  
400       CZE      203  
500       ERI      232

In [190]:
# 열추출 하기 
df.iloc[:,:-3]

country continent  year  lifeExp       pop
100      Bangladesh      Asia  1972   45.252  70759295
200    Burkina Faso    Africa  1992   50.260   8878303
300        Colombia  Americas  1952   50.643  12350771
400  Czech Republic    Europe  1972   70.290   9862158
500         Eritrea    Africa  1992   49.991   3668440