#### 2023-03-30

##### 1교시

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
a = np.array([[2,1,6],[0,7,4],[5,3,2]])
np.sort(a,axis=0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [10]:
a = np.arange(60).reshape(6,-1)[:,:6]
a 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [12]:
# 홀수만 고르면?
a[a%2==1]

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [21]:
# 망고와 멜론만 추출하시오.
df=pd.DataFrame([["cat", "mango"],["dog", "orange"],["lion", "melon"]],
             columns=["animal", "fruit"]) 
df

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

In [23]:
df["fruit"][::2]

0    mango
2    melon
Name: fruit, dtype: object

In [20]:
df.iloc[[0,2],[1]]

fruit
0  mango
2  melon

In [28]:
# name과 job에 열을 뽑아내시오.
df = pd.DataFrame([['John',25,'student'],['Cho',30,'teacher']],
                           columns= ['Name','Age','Job'])
df[["Name","Job"]]
df.loc[:,['Name','Job']]
df.iloc[:,::2] 

Name      Job
0  John  student
1   Cho  teacher

In [29]:
# np.min과 np.argmin의 차이를 설명하시오.

In [30]:
# np.min은 최솟값을 찾고 np.argmin은 최솟값의 인덱스를 찾는다 

In [31]:
a = np.array([[3,5,1],[2,4,6]])
a 

array([[3, 5, 1],
       [2, 4, 6]])

In [49]:
np.min(a)

1

In [50]:
np.argmin(a)

2

In [88]:
# 랜덤으로 행렬을 추출하시오.
import random
np.array(random.sample(range(25),k=25)).reshape(5,5)


array([[ 0,  6, 15,  9, 21],
       [17,  7, 20, 18, 13],
       [ 2, 19,  8,  4, 23],
       [ 3, 16, 11, 14, 24],
       [10, 22, 12,  5,  1]])

In [89]:
np.random.randint(0,25,size=(5,5))

array([[17, 17,  5,  3,  0],
       [17, 20,  5,  0, 21],
       [21,  4, 12,  6, 11],
       [ 1,  0, 21,  8, 19],
       [ 4, 14,  5, 20,  0]])

In [103]:
li=list(range(25))
random.shuffle(list(range(25)))
np.array(li).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
random.seed(1234)
a = np.array(random.sample(li,k=25)).reshape(5,5)
a 

array([[24, 14,  3,  0,  2],
       [18,  1, 20, 22, 11],
       [16, 21, 13, 12,  5],
       [ 9,  7,  8, 19, 15],
       [ 6, 10, 23,  4, 17]])

In [108]:
# a의 행별 최댓값을 구하시오.
np.max(a,1)

array([24, 22, 21, 19, 23])

##### 2교시

In [109]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [111]:
# 서준이의 점수를 전부 0점으로 만드시오.
df.loc[['서준']]=0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [128]:
import plotly.express as px
df= px.data.gapminder() 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
 6   iso_alpha  1704 non-null   object 
 7   iso_num    1704 non-null   int64  
dtypes: float64(2), int64(3), object(3)
memory usage: 106.6+ KB


In [129]:
a=df[:2]
a

country continent  year  lifeExp      pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801  8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332  9240934  820.853030       AFG   

   iso_num  
0        4  
1        4

In [130]:
# 나라이름과 대륙정보만 뽑아주세요.
a.loc[:,["country",'continent']]

country continent
0  Afghanistan      Asia
1  Afghanistan      Asia

In [131]:
# 이름을 '나라', '대륙'으로 수정해주세요.
df.rename(columns={"country":'나라','continent':'대륙'})

나라      대륙  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan    Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan    Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan    Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan    Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan    Asia  1972   36.088  13079460  739.981106       AFG   
...           ...     ...   ...      ...       ...         ...       ...   
1699     Zimbabwe  Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe  Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe  Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe  Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe  Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [135]:
# 뒤에 칼럼 세개를 삭제하시오.
df.iloc[:,:-3]

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [136]:
# 2002년 이후의 데이터만 추출하시오.
df[df.year>=2002]

country continent  year  lifeExp       pop    gdpPercap iso_alpha  \
10    Afghanistan      Asia  2002   42.129  25268405   726.734055       AFG   
11    Afghanistan      Asia  2007   43.828  31889923   974.580338       AFG   
22        Albania    Europe  2002   75.651   3508512  4604.211737       ALB   
23        Albania    Europe  2007   76.423   3600523  5937.029526       ALB   
34        Algeria    Africa  2002   70.994  31287142  5288.040382       DZA   
...           ...       ...   ...      ...       ...          ...       ...   
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906       YEM   
1690       Zambia    Africa  2002   39.193  10595811  1071.613938       ZMB   
1691       Zambia    Africa  2007   42.384  11746035  1271.211593       ZMB   
1702     Zimbabwe    Africa  2002   39.989  11926563   672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143   469.709298       ZWE   

      iso_num  
10          4  
11          4  
22          8  
23          8  
34         12  
...       ...  
1679      887  
1690      894  
1691      894  
1702      716  
1703      716  

[284 rows x 8 columns]

In [138]:
df = pd.DataFrame([[20,'AB','서울'],[25,'B','강원'],[27,'A','경기']],
                 index=['길동','춘향','몽룡'],
                 columns=['이름','혈액형','거주지']) 
df

이름 혈액형 거주지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

In [139]:
df[1:]

이름 혈액형 거주지
춘향  25   B  강원
몽룡  27   A  경기

In [142]:
# 거주지 열 이름을 '출생지'로 바꾸고 저장하시오.
df.rename(columns={'거주지':'출생지'})

이름 혈액형 출생지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

In [149]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

##### 3교시

##### 판다스 csv 파일 읽기

In [159]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [152]:
# 1. displacement -> displ
# 2. model-year -> year
# 3. year 75이상인 것만 뽑는다
# 4. 75 -> 1975로 만든다

In [167]:
#1,2
df.rename(columns={"displacement":'displ','model-year':'year'},inplace=True)
#3
df[df['year']>=75]
#4
df.year = df.year+1900

In [168]:
# df를 mpg.csv로 저장해주세요
df.to_csv()

',mpg,cylinders,displ,horsepower,weight,acceleration,year\r\n0,18.0,8,307.0,130.0,3504,12.0,7708\r\n1,15.0,8,350.0,165.0,3693,11.5,7708\r\n2,18.0,8,318.0,150.0,3436,11.0,7708\r\n3,16.0,8,304.0,150.0,3433,12.0,7708\r\n4,17.0,8,302.0,140.0,3449,10.5,7708\r\n5,15.0,8,429.0,198.0,4341,10.0,7708\r\n6,14.0,8,454.0,220.0,4354,9.0,7708\r\n7,14.0,8,440.0,215.0,4312,8.5,7708\r\n8,14.0,8,455.0,225.0,4425,10.0,7708\r\n9,15.0,8,390.0,190.0,3850,8.5,7708\r\n10,15.0,8,383.0,170.0,3563,10.0,7708\r\n11,14.0,8,340.0,160.0,3609,8.0,7708\r\n12,15.0,8,400.0,150.0,3761,9.5,7708\r\n13,14.0,8,455.0,225.0,3086,10.0,7708\r\n14,24.0,4,113.0,95.0,2372,15.0,7708\r\n15,22.0,6,198.0,95.0,2833,15.5,7708\r\n16,18.0,6,199.0,97.0,2774,15.5,7708\r\n17,21.0,6,200.0,85.0,2587,16.0,7708\r\n18,27.0,4,97.0,88.0,2130,14.5,7708\r\n19,26.0,4,97.0,46.0,1835,20.5,7708\r\n20,25.0,4,110.0,87.0,2672,17.5,7708\r\n21,24.0,4,107.0,90.0,2430,14.5,7708\r\n22,25.0,4,104.0,95.0,2375,17.5,7708\r\n23,26.0,4,121.0,113.0,2234,12.5,7708\r\n24,21

In [171]:
import os
os.getcwd()

'C:\\Users\\user\\Downloads'

In [176]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
df 

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [177]:
df['cylinders']

0      8
1      8
2      8
3      8
4      8
      ..
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

##### 5교시

##### 상관계수 구하기

In [178]:
df.corr()

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.777575 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.843751  0.896017   
displacement -0.804203   0.950721      1.000000    0.897787  0.932824   
horsepower   -0.777575   0.843751      0.897787    1.000000  0.864350   
weight       -0.831741   0.896017      0.932824    0.864350  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.687241 -0.417457   
model-year    0.579267  -0.348746     -0.370164   -0.420697 -0.306564   

              acceleration  model-year  
mpg               0.420289    0.579267  
cylinders        -0.505419   -0.348746  
displacement     -0.543684   -0.370164  
horsepower       -0.687241   -0.420697  
weight           -0.417457   -0.306564  
acceleration      1.000000    0.288137  
model-year        0.288137    1.000000

##### 결측치

In [ ]:
import seaborn as sns

In [182]:
titanic = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df=titanic.copy()
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [183]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [184]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [187]:
df.dropna(axis=1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
dtypes: float64(1), int64(5), object(3)
memory usage: 62.8+ KB


In [189]:
mean_age=df['Age'].mean()
df['Age'].fillna(mean_age,inplace=True)

In [190]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [191]:
df['Age'].isnull().sum()

0

In [192]:
E = pd.Series(['e0','e1','e2','e3'],name='e')
F = pd.Series(['f0','f1','f2'],name = 'f',index)
G = 

SyntaxError: positional argument follows keyword argument (929684631.py, line 2)

In [197]:
df1 = pd.DataFrame({'a':['a0','a1','a2'],
                   'b':['b0','b1','b2'],
                   'c':['c0','c1','c2']},
                  index = [0,1,2])
df2 = pd.DataFrame({'b':['b2','b3','b4'],
                   'c':['c2','c3','c4'],
                   'd':['d2','d3','d4']},
                   index = [1,2,3])

In [198]:
df1

a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [199]:
df2

b   c   d
1  b2  c2  d2
2  b3  c3  d3
3  b4  c4  d4

In [201]:
pd.concat([df1,df2])

a   b   c    d
0   a0  b0  c0  NaN
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
1  NaN  b2  c2   d2
2  NaN  b3  c3   d3
3  NaN  b4  c4   d4

In [204]:
pd.concat([df1, df2],axis=1)

a    b    c    b    c    d
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1   b2   c2   d2
2   a2   b2   c2   b3   c3   d3
3  NaN  NaN  NaN   b4   c4   d4

In [205]:
pd.concat([df1, df2],axis=1,join='inner') #교집합

a   b   c   b   c   d
1  a1  b1  c1  b2  c2  d2
2  a2  b2  c2  b3  c3  d3

In [206]:
# 칼럼 이름 소문자로 바꾸기
new_columns = []
for column in titanic.columns:
    new_columns.append(column.lower())
titanic.columns = new_columns    

In [207]:
titanic

passengerid  survived  pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  name     sex   age  sibsp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     parch            ticket     fare cabin embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [214]:
# 하나의 리스트에 담기 : names
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
              ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]
names=all_data[0]+all_data[1]
names

['John',
 'Emily',
 'Michael',
 'Mary',
 'Steven',
 'Maria',
 'Juan',
 'Javier',
 'Natalia',
 'Pilar']

In [217]:
# e가 두번 이상인 이름 나타내기

In [218]:
for name in names:
    if name.count('e')>=2:
        print(name)

Steven
