#### 2023-03-27

##### 1교시

strftime() 메소드로 현재 날짜/시간을 아래 형식의 스트링으로 변환하려면?

2023/03/24/17:46:01 12주차

In [11]:
import datetime
datetime.datetime.now().strftime("%Y/%m/%d %H:%M:%S %W주차") 

'2023/03/27 09:20:50 13주차'

In [3]:
#Q2.아래 데이터에서 hot으로 시작하는 음료만 추출하시오.

data='''
ice americano
hot americano
ice tea
hot tea
tea hot
ice milk
hot milk
milk hot
''' 

In [4]:
import re
p=re.compile("^hot.*",re.MULTILINE)
p.findall(data)

['hot americano', 'hot tea', 'hot milk']

In [12]:
data = [["영자", "옥순", "광수", "순자"],
            [80, 87, 85, 90],
            ["여자","여자","남자","여자"]] 
#에서 zip()를 사용하여 여자의 이름과 점수가 나오도록 출력하시오.

In [14]:
for i,j,k in zip(*data):
    if k == "여자":
        print(i, j) 

영자 80
옥순 87
순자 90


In [18]:
data = {"철수": 98,"영희": 80,"순이": 100,"돌이": 70,} 

In [20]:
for i,j in data.items():
    print(i,j)

철수 98
영희 80
순이 100
돌이 70


In [21]:
sum(data.values())/len(data.values())

87.0

import random
x = random.randint(1,10)
if x % 2 == 0:
    print("짝수")
else:
    print("홀수") 

In [66]:
x = random.randint(1,10)
print("짝수") if x % 2 == 0 else print("홀수") 

홀수


In [67]:
#슬라이싱을 이용해 다음 문자열에서 python을 출력해주세요
a = 'n$o$h$t_y*P' 

In [68]:
a[::-2]

'Python'

In [69]:
#immutable한 데이터 타입은?
# str, tuple

In [70]:
#덕 타이핑이란?
#객체 자료형보다는 객체가 할 수 있는 연산이나 행동에 관심을 두는 것 

In [71]:
#함수와 메서드의 차이는?
#함수:function(a)
#메서드:a.method()

##### 2교시

In [72]:
di={"apple":"사과"}
di

{'apple': '사과'}

In [73]:
#update를 써서 banana 바나나를 2가지 방법을 사용하여 추가합시다.

In [78]:
di.update({"banana":"바나나"})
di["banana"]="바나나"

In [79]:
di

{'apple': '사과', 'banana': '바나나'}

In [80]:
di.update({"cherry":"체리"})

In [81]:
di

{'apple': '사과', 'banana': '바나나', 'cherry': '체리'}

In [82]:
#key와 value를 바꾸어서 di1을 만들어 봅시다.
di1=dict()
for i,j in di.items():
    di1[j]=i
di1

{'사과': 'apple', '바나나': 'banana', '체리': 'cherry'}

In [83]:
words=['apple','bat','bar','atom','book']

In [84]:
by_letter=dict()
for word in words:
    letter=word[0]
    if letter not in by_letter:
        by_letter[letter]=[word]
    else:
        by_letter[letter].append(word)

In [85]:
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

a={1,2,3}
b={3,4,5}
#합집합
a.union(b)
a|b
#교집합
a.intersection(b)
a & b
#차집합
a.difference(b)
a - b
#대칭차집합
a.symmetric_difference(b)
a ^ b 

##### 3교시

In [91]:
#하나의 리스트로 바꾸어 봅시다.
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
            ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']] 

In [93]:
data=list()
for i in all_data:
    for j in i:
        print(j)
        data.append(j)
data
[j for i in all_data  for j in i]

John
Emily
Michael
Mary
Steven
Maria
Juan
Javier
Natalia
Pilar


['John',
 'Emily',
 'Michael',
 'Mary',
 'Steven',
 'Maria',
 'Juan',
 'Javier',
 'Natalia',
 'Pilar']

In [97]:
data=list()
for names in all_data:
    for name in names:
        data.append(name)
data
# 리스트 컴프리헨선으로 만들어 주세요.
[name for names in all_data  for name in names]
# 이름의 문자개수를 리스트 컴프리헨선으로 나타내면?
[len(name) for names in all_data  for name in names]
# 이름의 문자개수가 6개 이상인 이름만 모으면?
[name for names in all_data for name in names if len(name)>=6]
# 이름을 모두 대문자로 리스트 컴프리헨선으로 바꿔 주세요.
[name.upper() for names in all_data for name in names]

['JOHN',
 'EMILY',
 'MICHAEL',
 'MARY',
 'STEVEN',
 'MARIA',
 'JUAN',
 'JAVIER',
 'NATALIA',
 'PILAR']

In [98]:
li=['apple','banana','cherry']
di=dict()
for i,j in enumerate(li):
    di[i]=j
di

{0: 'apple', 1: 'banana', 2: 'cherry'}

In [100]:
li=['apple','banana','cherry']
{i:j for i,j in enumerate(li)}

{0: 'apple', 1: 'banana', 2: 'cherry'}

In [101]:
unique_length={len(name) for names in all_data for name in names}
unique_length

{4, 5, 6, 7}

In [102]:
li=[1,2,3,4]
def twice(x):
    return x*2

In [103]:
twice(3)

6

In [104]:
list(map(twice,li))

[2, 4, 6, 8]

In [115]:
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
       .....:           'south   carolina##', 'West virginia?'] 

In [120]:
import re
def clean_strings(strings):
    result=[]
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)
        value = value.title()
        result.append(value)
    return result

In [121]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [122]:
def remove_punctuation(value):
    return re.sub('[!#?]','',value)
clean_ops=[str.strip,remove_punctuation,str.title]

In [123]:
def clean_strings(strings, ops):
    result=[]
    for value in strings:
        for function in ops:
            value=function(value)
        result.append(value)
    return result

In [124]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [127]:
for i in map(remove_punctuation,states):
    print(i)

   Alabama 
Georgia
Georgia
georgia
FlOrIda
south   carolina
West virginia


##### 5교시

In [128]:
def add_numbers(x,y):
    return x+y

In [129]:
def add_five(x):
    return add_numbers(5,x)

In [130]:
add_five(10)

15

In [131]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [132]:
di={'a':1,'b':2,'c':3}

In [133]:
for i in di:
    print(i)

a
b
c


In [135]:
it=iter(di)
list(it)

['a', 'b', 'c']

In [155]:
def squares(n):
    for i in range(1,n+1):
        yield i

In [156]:
squares(10)

<generator object squares at 0x000001E5805B0580>

In [157]:
list(squares(10))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [158]:
# 0부터 입력된 수까지 연속된 자연수의 제곱을 만들어내는
# 제너레이터를 만들어 봅시다.
def _make_gen():
    for i in range(100):
        yield i**2
gen=_make_gen()

In [159]:
sum(x**2 for i in range(100))

900

In [160]:
import itertools
first_letter=lambda i:i[0]

In [161]:
names=['Alan','Adam','Wes','Will','Albert','Steven']

In [162]:
for letter,names in itertools.groupby(names,first_letter):
    print(letter,list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


##### 6교시

In [163]:
import numpy as np
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [164]:
type(a)

numpy.ndarray

In [165]:
a.shape

(4,)

In [166]:
a.ndim

1

In [167]:
a.dtype

dtype('int32')

In [169]:
a.nbytes

16

In [172]:
li=[0,1,2,3.0]
a=np.array(li,dtype='int32')
a

array([0, 1, 2, 3])

In [181]:
a=np.array([[0,1,2,3],[4,5,6,7]])
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [183]:
a.shape
a.size

8

In [184]:
a=np.arange(10)
a.shape

(10,)

In [191]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### 7교시

In [194]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [195]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [198]:
n=np.array([[[1,2],[3,4]],
         [[5,6],[7,8]]])

In [199]:
n.shape

(2, 2, 2)

In [200]:
np.arange(1,9).reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [205]:
np.arange(1,25).reshape(3,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [209]:
np.arange(8).reshape(4,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]]])

element-wise/column-wise/row-wise

In [210]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [211]:
a*b

array([ 5, 12, 21, 32])

In [212]:
a=np.array([1,2,3,4])
c=np.array([5])

In [213]:
a-c

array([-4, -3, -2, -1])

In [216]:
a=np.arange(4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
a*b #array

array([[ 0,  5],
       [12, 21]])

In [217]:
a@b #matrix

array([[ 6,  7],
       [26, 31]])

In [218]:
np.dot(a,b)

array([[ 6,  7],
       [26, 31]])

In [219]:
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [223]:
a=np.arange(5,9).reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [226]:
c=np.arange(36).reshape(3,4,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [227]:
a=np.arange(5,9).reshape(2,2)
b=np.array([[1,1],[1,1]])
a.dot(b)

array([[11, 11],
       [15, 15]])